### ISSUE TITLE
Issue when playing some YouTube searches

### ISSUE THREAD

**Issue by TechWhizZ199** [GoelBiju/pinybot#21]
This occurred with one specific search, it is an issue with the playlist retrieved, I will have to properly debug it later.

``` Python
[19:31:20] trillnz:!yt 200 % **
Exception in thread Thread - 264:
Traceback(most recent call last):
File "/usr/lib/python2.7/threading.py", line 801, 
in __bootstrap_inner self.run()

File "/usr/lib/python2.7/threading.py", line 754, 
in run self.__target(*self.__args, **self.__kwargs)
File "pinybot.py", line 1878, in do_play_media
_media = youtube.youtube_search(search_str)
File "/home/tech/pinybot-stable/api/youtube.py", line 35, in youtube_search
for item in api_response['content']['items']:
     TypeError:  string indices must be integers
```

**Comment by Autotonic** [comment]
its because of the %. Need to URL encode the search string.

**Comment by TechWhizZ199** [comment]
Thank you @Autotonic !

**Comment by GoelBiju** [comment]
Adding further to this issue, the specific response to the request is:

```html
<HTML>
<HEAD>
<TITLE>Bad Request</TITLE>
</HEAD>
<BODY BGCOLOR="#FFFFFF" TEXT="#000000">
<H1>Bad Request</H1>
<H2>Error 400</H2>
</BODY>
</HTML>
```
This HTML response cannot be parsed as a JSON response, so that is where the error is.

I have included a solution to this by importing quote_plus from urllib, and URL encoding the search term before posting the request. Thanks again @Autotonic .

**Comment by GoelBiju** [comment]
This has been solved for the new version by @nortxort.
