### ISSUE TITLE
General edits

### ISSUE THREAD

**Issue by Autotonic** [GoelBiju/pinybot#42]
Possible Solutions:
- [x] Less disk writes. We check the disk everytime someone types a message. Lets load this in memory then check.
- [x] Query the disk everytime a user joins and changes their nickname. Lets load this in memory instead of checking the file everytime.

**Comment by GoelBiju** [comment]
@Autotonic , I agree with less disk usage, there are various file operation's we can save to memory. I am unsure about what you mean by limiting request to an X amount of bytes. When we receive a response from the GoogleApis for YouTube, it must be a whole request in order to receive the JSON response (this is also essential for parsing the JSON formatted response).

**Comment by GoelBiju** [comment]
@nortxort has solved this issue with the new structure for pinylib and tinybot.
