### ISSUE TITLE
Include URL in !now command

### ISSUE THREAD

**Issue by Autotonic** [GoelBiju/pinybot#45]

**Comment by GoelBiju** [comment]
@Autotonic , this should be a small tweak which can be included in version 1.5.0. Thank you Aida!

**Comment by Webx123** [comment]
when i 1.5.0 coming out?

**Comment by GoelBiju** [comment]
@Webx123 , I am looking at a final release depending on the extent of the modifications to the RTMP library. Working in tandem with @nortxort, to perfect it, we are looking at several more weeks, and even then I am not sure, since I may be busy with other things.

UPDATE: The URL is now featured in the !now command @Autotonic .
